/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_acr_acrjni */

#ifndef _Included_com_example_acr_acrjni
#define _Included_com_example_acr_acrjni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_acr_acrjni
 * Method:    ACRLoadModelBuildNet
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_example_acr_acrjni_ACRLoadModelBuildNet
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     com_example_acr_acrjni
 * Method:    ACRWavDecode
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_example_acr_acrjni_ACRWavDecode
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_example_acr_acrjni
 * Method:    ACRFree
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_acr_acrjni_ACRFree
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
